<craft name="key">
	<parameter name="jawLength" default="4" type="int"/>
    <parameter name="sides" default="6" type="int"/>
    <parameter name="t" default="2" type="int"/>
	<script type = "text/openjscad">
    function main(params)
    {
        //vars
        var type = params.t || 1;

        var sides = params.sides || 6;
        
        var jaw_length = params.jawLength || 1;
        
        var pattern = params.pattern || [0,1,0,1,0,1,1,0,0];
        
        var ricasso_length = 0.4;
        //-----------------------
        
        var c = cube();
        
        c = linear_extrude({height : 0.125},circle({'fn':sides}).center(true));
        
        var rim = rotate_extrude({fn:sides}, square({size: [0.2,0.2], center: true}).translate([1,0,0]) );
        
        c = union(rim,c.center(true));
        
        //create jaw

        var jaw;
        var teeth;
        
        if(type != 1)
        {
            jaw = cube([jaw_length + ricasso_length + 1,1,0.125]).center([false,true,true]);
            jaw = union(jaw,cube([1/Math.sqrt(2),1/Math.sqrt(2),0.125]).rotateZ(45).translate([jaw_length+ricasso_length+1,0,0]).center([false,true,true]));

            //create teeth
            if(pattern.length && pattern.length>0){
                var width = jaw_length/pattern.length;
                for(var i = 0; i < pattern.length; i++)
                {
                    if(!pattern[i])
                    {
                        jaw = difference(jaw,cube([width/Math.sqrt(2),width/Math.sqrt(2),1]).center(true).rotateZ(45).translate([i*width + 1 + ricasso_length + width/2,-0.5,0]));
                    }
                }
            }

            var d = cube([jaw_length+1,0.1,0.1]).center([false,true,true]).translate([1+ricasso_length,0.25,0.075]);
            jaw = difference(jaw,group(d,d.mirroredZ()));
        }
        else
        {
            var jaw_radius = 0.175;
            jaw = cylinder({r: 1, h: jaw_length + ricasso_length});
            jaw = jaw.scale([jaw_radius,jaw_radius,1]);
            jaw = jaw.rotateY(90);
            jaw = union(jaw,sphere().scale(jaw_radius));
            jaw = union(jaw,sphere().scale(jaw_radius).translate([ricasso_length+jaw_length,0,0]))
            jaw = jaw.translate([1-ricasso_length,0,0]);
        
            //create teeth
            teeth = cube([3*jaw_length/8,1.5,0.15]).center(true);
            
            if(pattern.length && pattern.length>0){
                var width = (3*jaw_length/8)/pattern.length;
                for(var i = 0; i < pattern.length; i++)
                {
                    if(!pattern[i])
                    {
                        teeth = difference(teeth,cube([width*1.001,1,1]).translate([i*width-width*pattern.length/2,0.5,-0.5]));
                        teeth = difference(teeth,cube([width*1.001,1,1]).translate([width*pattern.length/2 - width - i*width,-1.5,-0.5]));
                    }
                }
            }
            
            teeth = teeth.translate([1 - 3*jaw_length/16 + jaw_length,0,0]);
            
            jaw = union(jaw,teeth);
        }
        
        //then add it to the first piece
        c = union(jaw,c);
        
        c = difference(c,cylinder({'r':0.15}).translate([-0.5,0,-0.5]));
        
        return c;
    }
	</script>
</craft>